# Generated by Django 4.2.29 on 2026-05-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='primary_color',
            field=models.CharField(default='#0d6efd', max_length=20),
        ),
    ]
