# Generated by Django 4.2.29 on 2026-04-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pinnedresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinnedresource',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
