# Generated by Django 4.2.29 on 2026-04-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pinnedresource_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinnedresource',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='pinnedresource',
            index=models.Index(fields=['profile', '-pinned_at'], name='core_pinned_profile_7f9905_idx'),
        ),
        migrations.AlterModelTable(
            name='pinnedresource',
            table=None,
        ),
    ]
