# Generated by Django 4.2.29 on 2026-04-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pinnedresource_url_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pinnedresource',
            name='core_pinned_profile_7f9905_idx',
        ),
        migrations.AddField(
            model_name='pinnedresource',
            name='resource_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
