RESOURCE_INFO = {
    'wellness': {
        'title': 'Wellness Services',
        'url': 'https://www.ccsu.edu/student-wellness-services',
        'description': 'Access mental health and wellness support.',
        'icon': 'fas fa-heart',
        'button': 'Visit',
        'btn_class': 'btn-primary',
        'roles': ['student'],
    },
    'degree-audit': {
        'title': 'Degree Audit',
        'url': '/dashboard/degree-audit/',
        'description': 'Track your academic progress and plan courses.',
        'icon': 'fas fa-chart-line',
        'button': 'View',
        'btn_class': 'btn-success',
        'roles': ['student'],
    },
    'financial-docs': {
        'title': 'Financial Documents',
        'url': '/dashboard/resource-unavailable/financial-docs/', # TODO: Implement this
        'description': 'View tuition, aid packages, and tax documents.',
        'icon': 'fas fa-dollar-sign',
        'button': 'View',
        'btn_class': 'btn-warning',
        'roles': ['student'],
    },
    'search-student': {
        'title': 'Search Student',
        'url': '/dashboard/search-student/',
        'description': 'Find students by name or ID.',
        'icon': 'fas fa-search',
        'button': 'Open',
        'btn_class': 'btn-primary',
        'roles': ['professor'],
    },
    'announcements': {
        'title': 'Announcements',
        'url': '/dashboard/create-announcement/',
        'description': 'Create announcements for students.',
        'icon': 'fas fa-bullhorn',
        'button': 'Open',
        'btn_class': 'btn-warning',
        'roles': ['professor'],
    },
    'course-management': {
        'title': 'Course Management',
        'url': '/dashboard/resource-unavailable/course-management/', # TODO: Implement this
        'description': 'Manage course materials and grading.',
        'icon': 'fas fa-book',
        'button': 'Open',
        'btn_class': 'btn-success',
        'roles': ['professor'],
    },
}