RESOURCE_INFO = {
    'degree-audit': {
        'title': 'Degree Audit',
        'url': '/dashboard/degree-audit/',
        'description': 'Track your academic progress and plan courses.',
        'icon': 'fas fa-chart-line',
        'button': 'View',
        'btn_class': 'btn-success',
        'roles': ['student'],
    },
    'financial-docs': {
        'title': 'Student Finances',
        'url': '/dashboard/financial-docs/',
        'description': 'View tuition, aid packages, and tax documents.',
        'icon': 'fas fa-dollar-sign',
        'button': 'View',
        'btn_class': 'btn-warning',
        'roles': ['student'],
    },
    'course-registration': {
        'title': 'Register for Classes',
        'url': '/dashboard/available-courses/',
        'description': 'View available courses and enroll in classes.',
        'icon': 'fas fa-book',
        'button': 'Register',
        'btn_class': 'btn-info',
        'roles': ['student'],
    },
    'search-student': {
        'title': 'Search Student',
        'url': '/dashboard/search-student/',
        'description': 'Find students by name or ID.',
        'icon': 'fas fa-search',
        'button': 'View',
        'btn_class': 'btn-primary',
        'roles': ['professor'],
    },
    'announcements': {
        'title': 'Announcements',
        'url': '/dashboard/announcements/',
        'description': 'View and manage announcements.',
        'icon': 'fas fa-bullhorn',
        'button': 'View',
        'btn_class': 'btn-warning',
        'roles': ['professor'],
    },
    'course-management': {
        'title': 'Course Management',
        'url': '/dashboard/courses/',
        'description': 'Manage course materials and grading.',
        'icon': 'fas fa-book',
        'button': 'Manage',
        'btn_class': 'btn-success',
        'roles': ['professor'],
    },
    'wellness': {
        'title': 'Wellness Services',
        'url': 'https://www.ccsu.edu/student-wellness-services',
        'description': 'Access mental health and wellness support.',
        'icon': 'fas fa-heart',
        'button': 'Visit',
        'btn_class': 'btn-primary',
        'roles': ['student', 'professor'],
    },
}