# Generated by Django 5.2.12 on 2026-04-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_studentrecord_email_alter_studentrecord_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorrecord',
            name='professor_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='student_id',
            field=models.IntegerField(unique=True),
        ),
    ]
