# Generated by Django 4.2.29 on 2026-04-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_course_section_course_unique_course_offering'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit_hours',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
